version: "3.7"

services:

  web:
    image: nginx
    volumes:
     - ./wordpress1.conf:/etc/nginx/conf.d/wordpress1.conf
     - ./ssl/:/etc/nginx/ssl/
    ports:
     - "80:80"
     - "443:443"

networks:
  default:
    external:
      name: internal
